import logoDarkImg from '../assets/images/logo-dark-mode.svg';
import logoImg from '../assets/images/logo.svg';

const light = {
  logo: logoImg,
  primaryColor: '#835afd',
  darkPrimaryColor: '#6F4BD8',
  secondaryColor: '#e559f9',
  asideColumnBackground: '#835afd',
  asideColumnFontColor: '#f8f8f8',
  mainColumnBackground: '#ffffff',
  mainColumnFontColor: '#ffffff',
  defaultBackground: '#ffffff',
  defaultFontColor: '#737380',
  defaultBoxShadow: '#835afd',
  inputBackground: '#ffffff',
  inputFontColor: '#29292e',
  inputPlaceholderColor: '#a8a8b3',
  inputBorder: '#a8a8b3',
  separator: '#a8a8b3',
  googleButtonBackground: '#ea4335',
  googleButtonBackgroundHover: '#c73327',
  buttonOutline: '#ffffff',
  buttonFontColor: '#ffffff',
  highlightFontColor: '#29292e',
  headerBorderColor: '#e2e2e2',
  headerCodeColor: '#835afd',
  headerCodeColorHover: '#e559f9',
  totalQuestionsFontColor: '#ffffff',
  defaultQuestionBackground: '#fefefe',
  defaultQuestionFontColor: '#737380',
  isQuestionAnswered: '#dbdcdd',
  isQuestionHighlighted: '#f4f0ff',
  deleteQuestion: '#e73f5d',
  linkColor: '#e559f9',
  linkColorHover: '#835afd',
  likeButtonFontColor: '#835afd',
  likeButtonFontColorHover: '#6F4BD8',
  svgStrokeColor: '#737380',
  svgStrokeColorHover: '#6F4BD8',
  svgFillColor: '#fefefe',
  svgFillColorHover: '#f4f0ff',
};

const dark = {
  logo: logoDarkImg,
  primaryColor: '#482b9e',
  darkPrimaryColor: '#4020a1',
  secondaryColor: '#e559f9',
  asideColumnBackground: '#482b9e',
  asideColumnFontColor: '#f8f8f8',
  mainColumnBackground: '#282a36',
  mainColumnFontColor: '#ffffff',
  defaultBackground: '#282a36',
  defaultFontColor: '#cfcfcf',
  defaultBoxShadow: '#e559f9',
  inputBackground: '#44475a',
  inputFontColor: '#f8f8f8',
  inputPlaceholderColor: '#a8a8b3',
  inputBorder: '#a8a8b3',
  separator: '#a8a8b3',
  googleButtonBackground: '#ea4335',
  googleButtonBackgroundHover: '#c73327',
  buttonOutline: '#ffffff',
  buttonFontColor: '#ffffff',
  highlightFontColor: '#ffffff',
  headerBorderColor: '#e2e2e2',
  headerCodeColor: '#bd93f9',
  headerCodeColorHover: '#e559f9',
  totalQuestionsFontColor: '#ffffff',
  defaultQuestionBackground: '#44475a',
  defaultQuestionFontColor: '#f8f8f8',
  isQuestionAnswered: '#262732',
  isQuestionHighlighted: '#251c40',
  deleteQuestion: '#e73f5d',
  linkColor: '#e559f9',
  linkColorHover: '#d67ee2',
  likeButtonFontColor: '#bd93f9',
  likeButtonFontColorHover: '#d67ee2',
  svgStrokeColor: '#a8a8b3',
  svgStrokeColorHover: '#bd93f9',
  svgFillColor: '#44475a',
  svgFillColorHover: '#282a36',
};

export const lightTheme = Object.freeze({ ...light });

export const darkTheme = Object.freeze({ ...dark });
